Disable test causing frequent failures on GitHub Actions
Summary:
On GitHub this test fails more often than it passes. Checked 3 previous failures and all had the same failure.

```
com.facebook.internal.ImageDownloaderTest > test remove before and after test adding request FAILED
    java.lang.AssertionError: expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at com.facebook.internal.ImageDownloaderTest.test remove before and after test adding request(ImageDownloaderTest.kt:76)
```

Reviewed By: joesus

Differential Revision: D40966876

fbshipit-source-id: c57eda4c4740dd62b342981807837e9898bba1aa