Replace usages of Future.cancel(true) with Future.cancel(false)
Summary:
Justification for the original task below.

# Future.cancel(true) considered harmful

The Future.cancel API takes a boolean indicating whether to interrupt the task if it's currently running. Please pass false only.

## DETAILS
Future.cancel(true) will interrupt the thread upon which the task is running. This is only safe to do if you can guarantee that all the code running within your task handles interrupts gracefully. If your code is running in FB4A (and probably other apps too, but I haven't checked), then you can't guarantee this. You may cause code running outside of your task, in a different thread, to fail mysteriously.In fact, any use of Thread.interrupt (other than invoking it on the current thread) can cause the same problem.

This logview trace is an example of what happens when a thread is interrupted and it's not handled gracefully. You can look into logcat and see more details. Here's a symbolicated view: P130429284

We use FileChannel when loading classes. FileChannel will throw ClosedByInterruptException if it's running within a thread that is interrupted. I'm going to catch/handle this one particular problem, but I'm not confident there aren't others.
Exceptions that result from attempts to load classes will be saved and re-thrown the next time the same class load is attempted. Which may be on a different thread. See [http://androidxref.com/.../art/runtime/class_linker.cc...](http://androidxref.com/9.0.0_r3/xref/art/runtime/class_linker.cc#208)

The ExecutorService API will normally ignore Throwables (unless afterExecute is overridden). This is potentially worse than a crash, since if a particular class is only used within an ExecutorService task, the resulting NoClassDefFoundError may never be detected. Instead the app will just silently fail to run such tasks. In the case of the pasted trace, the problem is initially ignored when it happens within the SocialWifiDetector$1 Runnable (which is run within a FutureTask), but is then detected when the same class load is attempted within TigonObservableRunnable (which is not within a FutureTask).

## Follow-ups:
T66631068 - Fix known causes of interrupts during classloading causing failures
T66631113 - Lint on usage of Future.cancel(true)
T66631161 - Replace usages of Future.cancel(true) with Future.cancel(false)
T66631218 - Soft error upon afterExecute if the Throwable is an Error
cc Delyan Kratunov, Austin Vandergon

Differential Revision: D25820813

fbshipit-source-id: 02ac273ea6e9a2ded9da58aaf27911c9331d685d